apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy # mongouser (echo -n mongouser | base64)
  mongo-password: bW9uZ29wYXNzd29yZA== # mongopassword (echo -n mongopassword | base64)

  
